# Generated by Django 6.0.4 on 2026-04-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_remove_alumno_curso_remove_alumno_grupo_inscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('accion', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('objeto_id', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
