# Generated by Django 6.0.4 on 2026-04-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_auditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='comuna',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
