# Generated by Django 6.0.4 on 2026-04-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_alumno_comuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
