# Generated by Django 6.0.4 on 2026-05-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_aviso'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='codigo_confirmacion',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='correo_confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
