# Generated by Django 6.0.4 on 2026-05-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0007_alumno_codigo_confirmacion_alumno_correo_confirmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='codigo_ingresado',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
