# Generated by Django 6.0.4 on 2026-05-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0008_alumno_codigo_ingresado'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='fecha_codigo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='intentos_codigo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='codigo_ingresado',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Código de confirmación'),
        ),
    ]
