# Generated by Django 6.0.4 on 2026-05-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0009_alumno_fecha_codigo_alumno_intentos_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='rut_confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
