# Generated by Django 6.0.4 on 2026-05-05 19:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0011_pago_cuota'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(blank=True, max_length=100, null=True)),
                ('concepto', models.CharField(max_length=200)),
                ('monto', models.PositiveIntegerField()),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cuota',
            options={'ordering': ['fecha_vencimiento']},
        ),
        migrations.RenameField(
            model_name='pago',
            old_name='fecha_creacion',
            new_name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='cuota',
            name='numero',
        ),
        migrations.AddField(
            model_name='cuota',
            name='numero_cuota',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='pago',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='monto',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pago',
            name='cantidad_cuotas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta'), ('OTRO', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto_total',
            field=models.PositiveIntegerField(),
        ),
    ]
