# Generated by Django 6.0.4 on 2026-05-06 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0012_gastooperacional_alter_cuota_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuota',
            options={'ordering': ['fecha_vencimiento'], 'permissions': [('can_edit_locked_cuotas', 'Puede editar cuotas ya ingresadas')]},
        ),
    ]
