# Generated by Django 6.0.4 on 2026-05-12 00:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0013_alter_cuota_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Legislación Aplicada', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PlanillaSPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(help_text='Ej: FGS352026. Se vinculará a este grupo.', max_length=50)),
                ('archivo_excel', models.FileField(help_text='Sube el archivo .xlsx de la SPD aquí', upload_to='planillas_spd/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False, help_text='Indica si el sistema ya leyó y creó las clases de este Excel')),
            ],
            options={
                'verbose_name': 'Planilla SPD',
                'verbose_name_plural': 'Planillas SPD (Carga de Clases)',
            },
        ),
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['apellidos', 'nombres']},
        ),
        migrations.AlterModelOptions(
            name='cuota',
            options={'ordering': ['fecha_vencimiento'], 'permissions': [('can_edit_locked_cuotas', 'Puede editar cuotas ya ingresadas')], 'verbose_name_plural': 'Listado de Deudores'},
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('RELATOR', 'Relator Autorizado'), ('FISCALIZADOR', 'Fiscalizador / Auditor')], max_length=20)),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('intentos_fallidos', models.IntegerField(default=0)),
                ('bloqueado', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SesionClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(help_text='Debe coincidir con el grupo de la inscripción', max_length=50)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('bloque_horario', models.CharField(help_text='Ej: 09:00 a 11:00', max_length=100)),
                ('horas_bloque', models.IntegerField(default=2)),
                ('modalidad', models.CharField(choices=[('ONLINE', 'Aula Virtual (Online)'), ('PRESENCIAL', 'Terreno (Presencial)')], default='ONLINE', max_length=20)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.modulo')),
                ('relator', models.ForeignKey(blank=True, limit_choices_to={'perfilusuario__rol': 'RELATOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_dictadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Clase',
                'verbose_name_plural': 'Programación de Clases (Calendario)',
                'ordering': ['fecha', 'bloque_horario'],
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.sesionclase')),
            ],
            options={
                'unique_together': {('alumno', 'sesion')},
            },
        ),
    ]
