# Generated by Django 6.0.4 on 2026-05-12 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0014_modulo_planillaspd_alter_alumno_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='modalidad_defecto',
            field=models.CharField(choices=[('ONLINE', 'Aula Virtual (Online)'), ('PRESENCIAL', 'Terreno (Presencial)')], default='ONLINE', max_length=20),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
