# Generated by Django 6.0.4 on 2026-05-12 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0015_modulo_modalidad_defecto_alter_modulo_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='modalidad_defecto',
        ),
    ]
