# Generated by Django 6.0.4 on 2026-05-12 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0016_remove_modulo_modalidad_defecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='pin',
            field=models.CharField(default='0000', help_text='PIN de 4 dígitos para acceso rápido', max_length=4),
        ),
    ]
