# Generated by Django 6.0.4 on 2026-05-12 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0017_perfilusuario_pin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={},
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='codigo_confirmacion',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='codigo_ingresado',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='correo_confirmado',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='fecha_codigo',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='intentos_codigo',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='rut_confirmado',
        ),
    ]
