# Generated by Django 6.0.4 on 2026-05-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0018_alter_alumno_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['apellidos', 'nombres']},
        ),
        migrations.AddField(
            model_name='alumno',
            name='codigo_confirmacion',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='codigo_ingresado',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Código de confirmación'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='correo_confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_codigo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='intentos_codigo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumno',
            name='rut_confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
