# Generated by Django 6.0.4 on 2026-05-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0019_alter_alumno_options_alumno_codigo_confirmacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuota',
            options={'ordering': ['fecha_vencimiento'], 'permissions': [('can_edit_locked_cuotas', 'Puede editar cuotas ya ingresadas')], 'verbose_name': 'Cuota / Deuda', 'verbose_name_plural': 'Listado de Deudores'},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'verbose_name': 'Cobro', 'verbose_name_plural': 'Cobros'},
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
