# Generated by Django 6.0.4 on 2026-05-13 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0020_alter_cuota_options_alter_pago_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
    ]
