# Generated by Django 6.0.4 on 2026-05-13 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0021_alter_pago_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditoria',
            options={'ordering': ['-fecha'], 'verbose_name': 'Auditoría', 'verbose_name_plural': 'Auditorías'},
        ),
    ]
