# Generated by Django 6.0.4 on 2026-05-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0022_alter_auditoria_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Documento')),
                ('codigo_referencia', models.SlugField(unique=True, verbose_name='Código de Referencia')),
                ('cuerpo_html', models.TextField(help_text='Usa variables como {{nombres}}, {{asistencia_modulo}}, etc.', verbose_name='Cuerpo del HTML')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Documento',
                'verbose_name_plural': '📂 Repositorio de Plantillas',
            },
        ),
    ]
